---
title: "Week 8 Lab - GitHub Tutorial"
author: "Craig"
date: "March 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)



```

##Column Graph of Texas Oil Spills

```{r}

oil_spills <- read_csv("oil_spills.csv")


df <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` < 2017) %>%  #filter the data to just be from Texas AND the year is less than 2017
  group_by(`Accident Year`) %>%   #Group the data by accident year.
  summarise(Loss = sum(`Net Loss (Barrels)`)) #Provide a summary of the net loss of barrels per group of years.


colnames(df) <- c("Year", "Loss")

ggplot(df, aes(x=Year, y=Loss))+
  geom_col()
```

Stage -> Commit -> Push

##Leaflet Plot of Spill Locations in Texas in 2016

```{r}

df_loc <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` == 2016) %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`)


colnames(df_loc) <- c("latitude", "longitude", "net_loss")

oil_sf <- st_as_sf(df_loc, coords = c("longitude", "latitude"), crs = 4326) #convert a dataframe into a simplefeatures spatial data.  identify the long and lat in the datafram and setting the coordinate reference system (crs) to WGS (code is 4326)

leaflet(oil_sf) %>% 
  addTiles() %>% 
  addMarkers()

```

